server:
  port: 8080

spring:
  application:
    name: realtimechat

  datasource:
    url: jdbc:mysql://localhost:3306/chatapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nirmit@99

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    shoe-sql: true