spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbcrud
    username: root
    password: Nirmit@99
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # Enables detailed Hibernate SQL logging
