server:
  port: 8080

spring:
  application:
    name: todolist

  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nirmit@99

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
