spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nirmit@99

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true